const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const CREATE_TASK = 'CREATE_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const SET_STATUSES = 'SET_STATUSES';
const SET_PRIORITIES = 'SET_PRIORITIES';
const SET_TASKS = 'SET_TASKS';
const SET_USERS = 'SET_USERS';
const SET_CURRENT_TASK = 'SET_CURRENT_TASK';

export default {
    LOGIN, LOGOUT,
    CREATE_TASK, UPDATE_TASK, DELETE_TASK, SET_CURRENT_TASK,
    SET_STATUSES, SET_PRIORITIES,
    SET_TASKS, SET_USERS
};
